const question = document.querySelector('.Question')
const options = document.querySelector('.options')
const option1 = document.querySelector('.option1')
const option2 = document.querySelector('.option2')
const option3 = document.querySelector('.option3')
const option4 = document.querySelector('.option4')
const counter = document.querySelector('.counter')
